version: "3.8"
services:
  queuer:
    image: "test_image"
    volumes:
    - ${ARTICLES_DIR}:/articles
    command: bash -c "python -u -m code.src.assigner"

  worker:
    image: "test_image"
    volumes:
      - ${ARTICLES_DIR}:/articles
    command: bash -c "python -u -m code.src.reader"

  writer:
    image: "test_image"
    volumes:
      - ${WORDS_DIR}:/tmp
    command: bash -c "python -u -m code.src.writer"