version: "3.8"
services:
  queuer:
    image: "test_image"
    volumes:
    - ${ARTICLES_DIR}:/articles
    command: bash -c "echo ${ARTICLES_DIR} && python -u -m code.src.assigner"

  worker:
    image: "test_image"
    volumes:
      - ${ARTICLES_DIR}:/articles
    command: bash -c "python -u -m code.src.reader"

  writer:
    image: "test_image"
    volumes:
      - ${WORDS_DIR}:/tmp
#      - /Users/adif/development/amenity/words:/tmp
    command: bash -c "python -u -m code.src.writer"